### PR TITLE
Propagates the context into requests

### PR DESCRIPTION
**Pull request by Barbayar**
TODO

### CODE REVIEW

**Comment by nineinchnick** [comment]
Here's my previous attempt at doing this: https://github.com/trinodb/trino-go-client/pull/96/commits/4c0e56c80ff7dd6fcc2cb7ba7babf7448c397f06

**Comment by Barbayar** [comment]
@nineinchnick Ah nice. Do you have any ETA on your change? For the context, we use Datadog to instrument our services, and noticed the distributed traces were breaking in `trino-go-client`.

**Comment by nineinchnick** [comment]
There are some open comments in the PR I linked. I don't have any ETA, I stopped working on that because no one asked for it.

**Comment by Barbayar** [comment]
Closing this in favor of https://github.com/trinodb/trino-go-client/pull/96.

**Pull request closed without merging**
