### PR TITLE
Allow passing X-Trino-Time-Zone header from config

### PR DESCRIPTION
**Pull request by Yifeng-Sigma**

### CODE REVIEW

**Review by nineinchnick — COMMENTED** [review]
Can you add some tests too? Ideally integration tests

**Comment by nineinchnick** [comment]
@Yifeng-Sigma can you add some tests? If not, I can take this over.

**Comment by Yifeng-Sigma** [comment]
> @Yifeng-Sigma can you add some tests? If not, I can take this over.

Hey, feel free to take this over, thank you.

**Comment by nineinchnick** [comment]
This should be fixed together with #119. I'll close it for now.

**Pull request closed without merging**
