### PR TITLE
Support UUIDs

### PR DESCRIPTION
**Pull request by JPMoresmau**
As described in https://trino.io/docs/current/language/types.html#uuid-type

### CODE REVIEW

**Review by nineinchnick — APPROVED** [review]
Thanks! I checked if the readme needs updating but it already says UUIDs are supported, so this fills a gap.

@losipiuk PTAL

**Review by losipiuk — APPROVED** [review]

**Comment by losipiuk** [comment]
Thanks! Did you already send your signed CLA as per https://github.com/trinodb/trino-go-client/pull/63#issuecomment-1336432071?

**Comment by JPMoresmau** [comment]
> Thanks! Did you already send your signed CLA as per [#63 (comment)](https://github.com/trinodb/trino-go-client/pull/63#issuecomment-1336432071)?

Yep, last week.

**Comment by ColmanHumphrey** [comment]
Just adding to this (and https://github.com/trinodb/trino-go-client/pull/62), we've (slight.co) also signed the corporate CLA and emailed it last week, with JP as a contributor. Thanks @losipiuk and @martint !

**Comment by losipiuk** [comment]
@cla-bot check

**Comment by losipiuk** [comment]
@cla-bot check

**Comment by losipiuk** [comment]
@martint ping regarding CLA

**Comment by JPMoresmau** [comment]
@cla-bot check

**Comment by losipiuk** [comment]
Release with a fix: https://github.com/trinodb/trino-go-client/releases/tag/v0.307.0

**Pull request merged**
