### PR TITLE
feat: Add option to pass credentials in as http header

### LINKED ISSUE #22: Add support to set X-Trino-Extra-Credential header
The Trino Go client does not provide a mechanism to set `extraCredentials`, which may be needed by some connectors. The Trino HTTP server expects to find a header named `X-Trino-Extra-Credential` per https://github.com/trinodb/trino/blob/8943325421e81990804a64c9f4f4fd1aaf3e2fc9/client/trino-client/src/main/java/io/trino/client/ProtocolHeaders.java#L131-L134

## Possible Solution

1. Extend the URL to accept a query parameter named `extraCredentials` that takes the form `key=value[,key=value,...]` per the requirements of the [Trino source](https://github.com/trinodb/trino/blob/8fb4a95ab491d91dc82f9a566eaa519ddbc2097a/core/trino-main/src/main/java/io/trino/server/HttpRequestSessionContext.java#L398)

2. Set the `X-Trino-Extra-Credential` header similar to here https://github.com/trinodb/trino-go-client/blob/67b9a8c818cc5327fb207e1c3cc5ee0acb84cc1e/trino/trino.go#L304

### PR DESCRIPTION
**Pull request by scbrickley**
Closes #22

### CODE REVIEW

**Comment by scbrickley** [comment]
Thanks for the quick response! I'll get those changes up ASAP.

**Comment by scbrickley** [comment]
How long does it usually take for the CLA bot to update? I sent in a CLA as requested about 20 minutes ago.

**Comment by scbrickley** [comment]
Got a confirmation that my CLA was accepted. Does we need to run the bot again to get the check to pass?

**Comment by martint** [comment]
@cla-bot check

**Review by hashhar — APPROVED** [review]
Thanks for the improvement @scbrickley. Please squash the changes into a single commit.

@losipiuk @nineinchnick Please take a look.

**Review by nineinchnick — APPROVED** [review]

**Review by losipiuk — APPROVED** [review]
Looks great. Thanks.

**Comment by losipiuk** [comment]
Merged as cbe5c3c (I droped `feat: ` from commit message)

**Comment by reedip** [comment]
Can we use this to pass JWT Token ? I don't see any option to authenticate with Bearer tokens

**Pull request closed without merging**
