### PR TITLE
When the data object of the Rows object is nil, the custom scanner object is not initialized.

### LINKED ISSUE #37: When the data object of the Rows object is nil, the custom scanner object is not initialized.
### Situation
As shown in the image below, when the data object of the Rows object is entered as `nil`, the custom scanner provided by trino does not initialize the existing data information and uses the previous data as it is.

스크린샷 2022-01-19 오후 7 06 00

Therefore, there is a problem that occurs when the data is `nil` but the value of valid is `true`.

### PR DESCRIPTION
**Pull request by Sunwoo-Shin**
Fixes #37

### CODE REVIEW

**Comment by Sunwoo-Shin** [comment]
> Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please submit the signed CLA to cla@trino.io. For more information, see https://github.com/trinodb/cla.

CLA had sent to cla@trino.io
( Sent Email: sunwoo.shin@navercorp.com )

**Comment by nineinchnick** [comment]
@cla-bot check

**Review by nineinchnick — APPROVED** [review]

**Comment by losipiuk** [comment]
LGTM - can you please rabase to address conflicts?

**Comment by Sunwoo-Shin** [comment]
@losipiuk 
> LGTM - can you please rabase to address conflicts?

rebased to the most recent branch.

**Comment by nineinchnick** [comment]
@Sunwoo-Shin can you rebase again? sorry about that but a fix was just merged for this failure in tests:
```
=== RUN   TestIntegrationUnsupportedHeader
    integration_test.go:490: unexpected error: trino: query failed (200 OK): "io.trino.spi.TrinoException: line 1:1: Session property 'grouped_execution' does not exist"
--- FAIL: TestIntegrationUnsupportedHeader (0.01s)
```

**Comment by Sunwoo-Shin** [comment]
@nineinchnick 
> can you rebase again? sorry about that but a fix was just merged for this failure in tests:

Rebased again.

**Pull request merged**
